
// Generated by Akka gRPC. DO NOT EDIT.
package sn.atos.wordline.project.demo.mtf.agent.Grpcservice;

import akka.grpc.ProtobufSerializer;
import akka.grpc.javadsl.GoogleProtobufSerializer;


public interface FileTransfertManager {
  
  
  java.util.concurrent.CompletionStage<sn.atos.wordline.project.demo.mtf.agent.Grpcservice.PostFileActionPerformed> postFile(sn.atos.wordline.project.demo.mtf.agent.Grpcservice.filePart in);
  
  
  java.util.concurrent.CompletionStage<sn.atos.wordline.project.demo.mtf.agent.Grpcservice.PostFileInfoActionPerformed> postFileinfo(sn.atos.wordline.project.demo.mtf.agent.Grpcservice.fileInfo in);
  

  static String name = "FileTransfertManager.FileTransfertManager";

  public static class Serializers {
    
      public static ProtobufSerializer<sn.atos.wordline.project.demo.mtf.agent.Grpcservice.filePart> filePartSerializer = new GoogleProtobufSerializer<>(sn.atos.wordline.project.demo.mtf.agent.Grpcservice.filePart.class);
    
      public static ProtobufSerializer<sn.atos.wordline.project.demo.mtf.agent.Grpcservice.fileInfo> fileInfoSerializer = new GoogleProtobufSerializer<>(sn.atos.wordline.project.demo.mtf.agent.Grpcservice.fileInfo.class);
    
      public static ProtobufSerializer<sn.atos.wordline.project.demo.mtf.agent.Grpcservice.PostFileActionPerformed> PostFileActionPerformedSerializer = new GoogleProtobufSerializer<>(sn.atos.wordline.project.demo.mtf.agent.Grpcservice.PostFileActionPerformed.class);
    
      public static ProtobufSerializer<sn.atos.wordline.project.demo.mtf.agent.Grpcservice.PostFileInfoActionPerformed> PostFileInfoActionPerformedSerializer = new GoogleProtobufSerializer<>(sn.atos.wordline.project.demo.mtf.agent.Grpcservice.PostFileInfoActionPerformed.class);
    
  }
}
