
// Generated by Akka gRPC. DO NOT EDIT.
package sn.atos.wordline.project.demo.mtf.agent.Grpcservice;


import akka.grpc.javadsl.SingleResponseRequestBuilder;


public abstract class FileTransfertManagerClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer postFile(com.example.demo.FTPserver.ftpGrpc.filePart) if possible.
     */
    
      public SingleResponseRequestBuilder<sn.atos.wordline.project.demo.mtf.agent.Grpcservice.filePart, sn.atos.wordline.project.demo.mtf.agent.Grpcservice.PostFileActionPerformed> postFile()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer postFileinfo(com.example.demo.FTPserver.ftpGrpc.fileInfo) if possible.
     */
    
      public SingleResponseRequestBuilder<sn.atos.wordline.project.demo.mtf.agent.Grpcservice.fileInfo, sn.atos.wordline.project.demo.mtf.agent.Grpcservice.PostFileInfoActionPerformed> postFileinfo()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
}
